# Generated by Django 5.1.6 on 2025-02-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("order_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("email", models.EmailField(max_length=254)),
                ("addr", models.TextField(max_length=200)),
            ],
        ),
    ]
