# Generated by Django 5.1.6 on 2025-02-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuestionPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_name", models.CharField(max_length=255)),
                ("question_number", models.IntegerField()),
                ("subject", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["question_number"],
            },
        ),
    ]
