# Generated by Django 5.1.6 on 2025-02-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Q1_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="stock",
            new_name="quantity",
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(max_length=500),
        ),
    ]
