apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-mongo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-mongo-api
  template:
    metadata:
      labels:
        app: flask-mongo-api
    spec:
      containers:
        - name: flask-mongo-api
          image: ag1121/flask-mongo-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5001