apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    run: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
