# Generated by Django 5.1.6 on 2025-02-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_holder",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[("SAVINGS", "Savings"), ("CURRENT", "Current")], max_length=20
            ),
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
