# Generated by Django 5.1.6 on 2025-02-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="F1Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("driver_name", models.CharField(max_length=100)),
                ("team", models.CharField(max_length=100)),
                ("car_number", models.IntegerField(unique=True)),
                ("championship_points", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-championship_points"],
            },
        ),
    ]
